export default {
  colors: {
    text: '#000',
    secondaryText: '#2c2c32ff',
    placeholderText: 'gray',
    background: '#fff',
    backgroundScroll: '#b0b2c376',
    defaultBackground: 'transparent',
    tintPrimary: '#464AB7',
    tintSecondary: '#FFE156',
    tintOK: '#DBF4A7',
    tintError: '#FC6471',
    tintDefault: '#fff',
    tabIconBackgroundDefault: '#b0b2c376',
    tabIconBackgroundSelected: '#b6b7f179',
    tabIconDefault: '#fff',
    tabIconSelected: '#464AB7',
    modalBackground: '#A1A3F6',
    modalBackgroundOpacity: '#a1a2f67d',
  },
  spacing: {
    small: 4,
    medium: 8,
    large: 16,
    extraLarge: 32,
  },
};
